sonar.organization=rajivadvika
sonar.projectKey=rajivadvika_cute-sparkle-folio
sonar.projectName=cute-sparkle-folio

# Path to the source directories
sonar.sources=src
sonar.exclusions=node_modules/**, dist/**, build/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8